// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $api_mcp from "./routes/api/mcp.ts";
import * as $index from "./routes/index.tsx";
import * as $search from "./routes/search.tsx";
import { type Manifest } from "fresh";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/api/mcp.ts": $api_mcp,
    "./routes/index.tsx": $index,
    "./routes/search.tsx": $search,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
